project:
  type: website

website:
  title: "Welcome to my dataxguru Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/leonatopl
      - icon: twitter
        href: https://twitter.com/pleonato
      - icon: linkedin
        href: https://linkedin.com/pleonato
    left:
      - text: Home-blog
        file: index.qmd
      - resume.qmd
      - projects.qmd
  google-analytics: "G-L4WJJ84KT0"
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

